### ISSUE TITLE
The icon does not change

### ISSUE THREAD

**Issue by robman70** [EddyVerbruggen/cordova-plugin-app-icon-changer#10]
Hi,
it looks like a really interesting plugin but I have a problem: the confirmation message says that the icon has been changed, but the icon does not change. The icon file looks correct, because, if I change its name, it appears a message indicating that the file name is wrong and yet, even the confirmation window displays the default icon, not the new one.
I created only one 'new' icon file (196*196) named '**unico.png**' and placed it into **./platforms/ios/<project_name>/Resources** and in **./platforms/ios/<project_name>/Resources/Resources** (I have twice, I don't know why).

What am I doing wrong?

JS Code:

	AppIconChanger.isSupported(
		function (supported) {
			AppIconChanger.changeIcon(
				{
					iconName: 'unico',
					suppressUserNotification: false
				},
				function () { console.log("OK"); },
				function (err) { console.log(err); }
			);
		}
	);

This is the code that I've added to my app .plist:

	<key>CFBundleIcons</key>
	<dict>
		<key>CFBundleAlternateIcons</key>
		<dict>
			<key>unico</key>
			<dict>
				<key>UIPrerenderedIcon</key>
				<true/>
				<key>CFBundleIconFiles</key>
				<array>
					<string>unico</string>
				</array>
			</dict>
		</dict>
	</dict>

**Comment by robman70** [comment]
Can anyone help me?

**Comment by mgoetz85** [comment]
I had the same issue - basically it was caused because the icon file was not included in the build as a resource.

I added the following snippet to my config and it works now:

`
 <platform name="ios">
   ...
   <custom-preference func="addResourceFile" name="ios-xcodefunc">
      <arg flag="path" type="String" value="www/res/alticon.png"/>
   </custom-preference>
</platform>
`
