### ISSUE TITLE
How to check if AppIconChanger is available

### ISSUE THREAD

**Issue by inexuscore** [EddyVerbruggen/cordova-plugin-app-icon-changer#2]
Hi I'm using this plugin on a Ionic 1.3.2 project with Cordova 6.x.
I've installed the plugin but when I call the *isSupported()* method nothing happens.  
I don't get any JavaScript error either so, how I check if the object is available?  
P.S I'm testing the app on a Android 6 device, so I just need to see if its available or not.  

This is my service method, pretty straight-forward.  
```
 isSupported(): ng.IPromise<boolean> {
            console.log('AlternateIconService.isSupported() reached');

            let d = this.$q.defer();

            this.$ionicPlatform.ready(() => {
                console.log('ionic platform ready. check app-icon-changer');

                console.log('AppIconChanger', AppIconChanger);

                AppIconChanger.isSupported((supported) => {
                    console.log("AppIconChanger.isSupported()", supported);
                    d.resolve(supported);
                });
            });

            return d.promise;
        }
```

**Comment by EddyVerbruggen** [comment]
This plugin is for iOS only so you can check that.

**Comment by inexuscore** [comment]
yup I had to handle the error callback. it returns *class not found*.  
cheers
