### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by antgel** [EddyVerbruggen/cordova-plugin-app-icon-changer#5]
We have a single Cordova app for all our ~800 customers. We want the launcher icon to change once they select their school. We hope that this plugin will work even though it's old. But for Android, we're stuck. Does anyone know how to do this on Android? We'd be happy to pay anyone who can code this.

**Comment by antgel** [comment]
@EddyVerbruggen Thanks for the quick response. According to my subsequent research, it's not possible to change the icon dynamically on Android, irrespective of Cordova. So closing this.

**Comment by kd8ssq** [comment]
@EddyVerbruggen would you be able to utilize information in this project to make it work for android devices in your plugin?

https://github.com/myinnos/AppIconNameChanger
