### ISSUE TITLE
plugin is not changing the icon. 

### ISSUE THREAD

**Issue by msmadja** [EddyVerbruggen/cordova-plugin-app-icon-changer#7]
The plugin is not changing the icon to the right one.
the plugin showing me success message 'your icon have changed' but nothing happen after I click on 'ok' button.

I tried to debug this in the Xcode IDE and I saw that after the 'OK' clicked it return nil object.

![WhatsApp Image 2019-03-24 at 12 36 42](https://user-images.githubusercontent.com/12684470/54878241-96fcec00-4e32-11e9-985b-e147846065e6.jpeg)

![WhatsApp Image 2019-03-24 at 12 36 23](https://user-images.githubusercontent.com/12684470/54878242-99f7dc80-4e32-11e9-9ec4-65c5ad1ba0ec.jpeg)

My code is:
```
 if (gwCordovaService.isCordova) {
        AppIconChanger.isSupported((supported) => {
          console.info("AppIconChanger Supported? " + supported);
          AppIconChanger.changeIcon(
            {
              iconName: `icon_${ containerCustomer.app_id }`,
              suppressUserNotification: true
            },
            () => {
              console.log("icon Updated");
            },
            (err) => {
              console.log(err)
             }
          );
        });
      }
```
I run this code in Angular 6 framework after device ready called.
also I run this on Iphone 7 on debug mode. using USB cable and development provision profile.

**Comment by sin-tanaka** [comment]
@msmadja It worked for My environment.

Do you add `*-info-plist > CFBundleIcons` and IconImageFile to root of `Resource` directory?

Ref: https://github.com/EddyVerbruggen/cordova-plugin-app-icon-changer#preparing-your-app-for-icon-switching

**Comment by msmadja** [comment]
@sin-tanaka sure. I solved it.  
My problem was wrong path of  the images.
I close this issue.
Tnx for your help.
